import { rotatedRectBounds, type BoardNode, type BoardDocument, type BoardChangeSet, type WorldBounds, type Point, type AssetRef, type NodeTypeRegistry } from "@pixi-board/core";
import { NodeRendererRegistry } from "./registry";
import { registerBuiltinRenderers } from "./builtins";
import type { CullingQuery, PixiApplication, PixiApplicationFactory, PixiDisplayObject, PixiNodeRendererContext, PixiNodeView, PixiViewFactory, RendererDiagnostics, TextureLease } from "./types";
import { createPixiApplicationFactory, createPixiViewFactory, loadPixiRuntime } from "./pixi-adapter";
type Entry = { node: Readonly<BoardNode>; view: PixiNodeView; renderer: any; controller: AbortController; generation: number };
export type PixiBoardRendererOptions = { applicationFactory?: PixiApplicationFactory; viewFactory?: PixiViewFactory; cullingQuery?: CullingQuery; acquireTexture?: (ref: AssetRef, options?: Record<string, unknown>) => Promise<TextureLease>; onInvalidate?: () => void; registry?: NodeRendererRegistry; nodeTypes?: NodeTypeRegistry };
export class PixiBoardRenderer {
  readonly registry: NodeRendererRegistry; readonly diagnostics: RendererDiagnostics = { creates: 0, updates: 0, destroys: 0, lateUpdates: 0 }; readonly activeViews = new Map<string, PixiNodeView>();
  private readonly options: PixiBoardRendererOptions; private readonly instanceAbort = new AbortController(); private readonly entries = new Map<string, Entry>(); private app?: PixiApplication; private world?: PixiDisplayObject; private snapshot?: Readonly<BoardDocument>; private visibleBounds?: WorldBounds; private destroyed = false; private viewFactory?: PixiViewFactory;
  constructor(options: PixiBoardRendererOptions) { this.options = options; this.registry = options.registry ?? new NodeRendererRegistry(); registerBuiltinRenderers(this.registry); }
  async init(): Promise<void> { if (this.destroyed) throw new Error("Renderer has been destroyed"); const applicationFactory = this.options.applicationFactory ?? createPixiApplicationFactory(); this.app = await applicationFactory(); await this.app.init?.({ preference: "webgl", antialias: false, powerPreference: "high-performance", ...this.app.initOptions }); const pixi = this.options.viewFactory ? undefined : await loadPixiRuntime(); this.viewFactory = this.options.viewFactory ?? createPixiViewFactory(pixi!); this.world = this.viewFactory.createContainer(); this.app.stage.addChild?.(this.world); }
  async rebuild(snapshot: Readonly<BoardDocument>): Promise<void> { this.assertAlive(); this.snapshot = snapshot; for (const id of [...this.entries.keys()]) await this.destroyView(id); await this.reconcileActiveSet(); }
  async apply(snapshot: Readonly<BoardDocument>, changeSet?: BoardChangeSet): Promise<void> { this.assertAlive(); if (!changeSet || !this.snapshot || changeSet.revision !== this.snapshot.revision + 1) return this.rebuild(snapshot); this.snapshot = snapshot; await this.reconcileActiveSet(); await this.applyCulling(); }
  async setVisibleBounds(bounds: WorldBounds | undefined): Promise<void> { this.visibleBounds = bounds; await this.reconcileActiveSet(); await this.applyCulling(); }
  setCullingQuery(query: CullingQuery | undefined): void { this.options.cullingQuery = query; }
  async refreshRegisteredTypes(): Promise<void> { if (this.snapshot) await this.rebuild(this.snapshot); }
  getBounds(node: Readonly<BoardNode>): WorldBounds { const definition = this.options.nodeTypes?.get(node.type); return definition ? definition.getBounds(node as BoardNode<any>) : rotatedRectBounds(node); }
  hitTest(worldPoint: Point): string | undefined {
    const order = this.snapshot?.nodes.map((node, index) => ({ node, index })).filter(({ node }) => this.entries.has(node.id)).sort((a, b) => b.node.zIndex - a.node.zIndex || b.index - a.index) ?? [...this.entries.values()].map((entry, index) => ({ node: entry.node, index })).sort((a, b) => b.node.zIndex - a.node.zIndex || b.index - a.index);
    for (const { node } of order) { const entry = this.entries.get(node.id)!; if (entry.renderer.hitTest?.(node, worldPoint) ?? contains(rotatedRectBounds(node), worldPoint)) return node.id; }
    return undefined;
  }
  async destroy(): Promise<void> { if (this.destroyed) return; this.destroyed = true; this.instanceAbort.abort(); for (const id of [...this.entries.keys()]) await this.destroyView(id); this.world?.destroy?.({ children: true }); this.app?.destroy?.(true); this.entries.clear(); this.activeViews.clear(); }
  private async ensureView(node: Readonly<BoardNode>): Promise<void> { const renderer = this.registry.get(node.type) ?? this.registry.get("unknown-node")!; const current = this.entries.get(node.id); if (current && current.renderer === renderer && sameAssetRefs(current.node.assetRefs, node.assetRefs)) { current.node = node; const generation = ++current.generation; this.diagnostics.updates++; await renderer.update(current.view, node, this.context(current.controller.signal)); if (this.entries.get(node.id) !== current || current.generation !== generation) this.diagnostics.lateUpdates++; return; } if (current) await this.destroyView(node.id); const controller = new AbortController(); const signal = mergeSignals(this.instanceAbort.signal, controller.signal); const context = this.context(signal); const view = await renderer.create(node, context); if (this.destroyed || signal.aborted) { this.diagnostics.lateUpdates++; renderer.destroy(view, context); return; } const entry: Entry = { node, view, renderer, controller, generation: 1 }; this.entries.set(node.id, entry); this.activeViews.set(node.id, view); this.world?.addChild?.(view.displayObject); this.diagnostics.creates++; await renderer.update(view, node, context); }
  private async destroyView(id: string): Promise<void> { const entry = this.entries.get(id); if (!entry) return; entry.controller.abort(); this.entries.delete(id); this.activeViews.delete(id); this.world?.removeChild?.(entry.view.displayObject); entry.renderer.destroy(entry.view, this.context(entry.controller.signal)); this.diagnostics.destroys++; }
  private async applyCulling(): Promise<void> { if (!this.visibleBounds) return; const visible = this.options.cullingQuery ? new Set(this.options.cullingQuery(this.visibleBounds)) : undefined; for (const [id, entry] of this.entries) entry.view.displayObject.visible = visible ? visible.has(id) : true; }
  private async reconcileActiveSet(): Promise<void> { if (!this.snapshot) return; const retained = new Set<string>(); for (const node of this.snapshot.nodes) { if (this.shouldActivate(node)) { retained.add(node.id); await this.ensureView(node); } } for (const id of [...this.entries.keys()]) if (!retained.has(id)) await this.destroyView(id); }
  private shouldActivate(node: Readonly<BoardNode>): boolean { return node.visible !== false && (!this.visibleBounds || !this.options.cullingQuery || new Set(this.options.cullingQuery(this.visibleBounds)).has(node.id)); }
  private context(signal: AbortSignal): PixiNodeRendererContext { if (!this.viewFactory) throw new Error("Renderer is not initialized"); return { signal, assets: { acquireTexture: this.options.acquireTexture ?? (async () => ({})) }, invalidate: () => this.options.onInvalidate?.(), lod: {}, diagnostics: this.diagnostics, display: this.viewFactory }; }
  private assertAlive(): void { if (this.destroyed) throw new Error("Renderer has been destroyed"); if (!this.app) throw new Error("Renderer is not initialized"); }
}
function contains(b: WorldBounds, p: Point): boolean { return p.x >= b.minX && p.x <= b.maxX && p.y >= b.minY && p.y <= b.maxY; }
function mergeSignals(...signals: AbortSignal[]): AbortSignal { const controller = new AbortController(); const abort = () => controller.abort(); for (const signal of signals) { if (signal.aborted) controller.abort(); else signal.addEventListener("abort", abort, { once: true }); } return controller.signal; }
function sameAssetRefs(a: BoardNode["assetRefs"], b: BoardNode["assetRefs"]): boolean { return JSON.stringify(a ?? {}) === JSON.stringify(b ?? {}); }
