import { rotatedRectBounds, type BoardNode, type BoardDocument, type BoardChangeSet, type WorldBounds, type Point, type AssetRef, type NodeTypeRegistry } from "@pixi-board/core";
import { NodeRendererRegistry } from "./registry";
import { registerBuiltinRenderers } from "./builtins";
import { GridSpatialIndex } from "./spatial";
import type { CaptureAdapter, CaptureRequest, CullingQuery, PixiApplication, PixiApplicationFactory, PixiDisplayObject, PixiNodeRendererContext, PixiNodeView, PixiViewFactory, RendererCaptureResult, RendererDiagnostics, SpatialIndex, TextureLease } from "./types";
import { createPixiApplicationFactory, createPixiViewFactory, loadPixiRuntime } from "./pixi-adapter";
type Entry = { node: Readonly<BoardNode>; view: PixiNodeView; renderer: any; controller: AbortController; generation: number };
export type PixiBoardRendererOptions = { applicationFactory?: PixiApplicationFactory; viewFactory?: PixiViewFactory; cullingQuery?: CullingQuery; spatialIndex?: SpatialIndex; capture?: CaptureAdapter; acquireTexture?: (ref: AssetRef, options?: Record<string, unknown>) => Promise<TextureLease>; onInvalidate?: () => void; registry?: NodeRendererRegistry; nodeTypes?: NodeTypeRegistry };
export class PixiBoardRenderer {
  readonly registry: NodeRendererRegistry; readonly diagnostics: RendererDiagnostics = { creates: 0, updates: 0, destroys: 0, lateUpdates: 0 }; readonly activeViews = new Map<string, PixiNodeView>();
  private readonly options: PixiBoardRendererOptions; private readonly instanceAbort = new AbortController(); private readonly entries = new Map<string, Entry>(); private app?: PixiApplication; private world?: PixiDisplayObject; private snapshot?: Readonly<BoardDocument>; private readonly nodesById = new Map<string, Readonly<BoardNode>>(); private visibleBounds?: WorldBounds; private destroyed = false; private viewFactory?: PixiViewFactory;
  readonly spatialIndex: SpatialIndex;
  constructor(options: PixiBoardRendererOptions) { this.options = options; this.registry = options.registry ?? new NodeRendererRegistry(); this.spatialIndex = options.spatialIndex ?? new GridSpatialIndex(); registerBuiltinRenderers(this.registry); }
  async init(): Promise<void> { if (this.destroyed) throw new Error("Renderer has been destroyed"); const applicationFactory = this.options.applicationFactory ?? createPixiApplicationFactory(); this.app = await applicationFactory(); await this.app.init?.({ preference: "webgl", antialias: false, powerPreference: "high-performance", ...this.app.initOptions }); const pixi = this.options.viewFactory ? undefined : await loadPixiRuntime(); this.viewFactory = this.options.viewFactory ?? createPixiViewFactory(pixi!); this.world = this.viewFactory.createContainer(); this.app.stage.addChild?.(this.world); }
  async rebuild(snapshot: Readonly<BoardDocument>): Promise<void> { this.assertAlive(); this.snapshot = snapshot; this.nodesById.clear(); for (const node of snapshot.nodes) this.nodesById.set(node.id, node); this.rebuildSpatialIndex(snapshot); for (const id of [...this.entries.keys()]) await this.destroyView(id); await this.reconcileActiveSet(); }
  async apply(snapshot: Readonly<BoardDocument>, changeSet?: BoardChangeSet): Promise<void> { this.assertAlive(); if (!changeSet || !this.snapshot || changeSet.revision !== this.snapshot.revision + 1) return this.rebuild(snapshot); this.snapshot = snapshot; this.nodesById.clear(); for (const node of snapshot.nodes) this.nodesById.set(node.id, node); this.rebuildSpatialIndex(snapshot); await this.reconcileActiveSet(); await this.applyCulling(); }
  async setVisibleBounds(bounds: WorldBounds | undefined): Promise<void> { this.visibleBounds = bounds; await this.reconcileActiveSet(); await this.applyCulling(); }
  setCullingQuery(query: CullingQuery | undefined): void { this.options.cullingQuery = query; }
  async refreshRegisteredTypes(): Promise<void> { if (this.snapshot) await this.rebuild(this.snapshot); }
  getBounds(node: Readonly<BoardNode>): WorldBounds { const definition = this.options.nodeTypes?.get(node.type); return definition ? definition.getBounds(node as BoardNode<any>) : rotatedRectBounds(node); }
  hitTest(worldPoint: Point): string | undefined {
    const ids = this.spatialIndex.queryPoint?.(worldPoint) ?? this.entries.keys();
    const order = [...ids].map((id, index) => ({ node: this.entries.get(id)?.node, index })).filter(({ node }) => node).sort((a, b) => b.node!.zIndex - a.node!.zIndex || b.index - a.index);
    for (const { node } of order) { const entry = this.entries.get(node!.id)!; if (entry.renderer.hitTest?.(node, worldPoint) ?? contains(this.getBounds(node!), worldPoint)) return node!.id; }
    return undefined;
  }
  async capture(request: CaptureRequest, options: { signal?: AbortSignal; requestId?: string } = {}): Promise<RendererCaptureResult> {
    this.assertAlive(); const signal = options.signal ?? new AbortController().signal; if (signal.aborted) throw new DOMException("Aborted", "AbortError");
    const scale = request.scale ?? 1; if (!Number.isFinite(scale) || scale <= 0) throw new RangeError("Capture scale must be positive");
    let target = this.world!; let frame: WorldBounds | undefined;
    if (request.target === "node") { const node = this.snapshot?.nodes.find((item) => item.id === request.nodeId); if (!node) throw new Error(`Node ${request.nodeId} does not exist`); const temporary = !this.entries.has(node.id); if (temporary) await this.ensureView(node); const entry = this.entries.get(node.id); if (!entry) throw new Error(`Node ${request.nodeId} is not available for capture`); target = entry.view.displayObject; frame = { minX: 0, minY: 0, maxX: node.width, maxY: node.height }; try { return await this.captureFrame(target, frame, scale, request, signal, options.requestId); } finally { if (temporary) await this.destroyView(node.id); } }
    if (request.target === "bounds") frame = request.bounds;
    return this.captureFrame(target, frame, scale, request, signal, options.requestId);
  }
  async destroy(): Promise<void> { if (this.destroyed) return; this.destroyed = true; this.instanceAbort.abort(); for (const id of [...this.entries.keys()]) await this.destroyView(id); this.world?.destroy?.({ children: true }); this.app?.destroy?.(true); this.entries.clear(); this.activeViews.clear(); }
  private async ensureView(node: Readonly<BoardNode>): Promise<void> { const renderer = this.registry.get(node.type) ?? this.registry.get("unknown-node")!; const current = this.entries.get(node.id); if (current && current.renderer === renderer && sameAssetRefs(current.node.assetRefs, node.assetRefs)) { current.node = node; const generation = ++current.generation; this.diagnostics.updates++; await renderer.update(current.view, node, this.context(current.controller.signal)); if (this.entries.get(node.id) !== current || current.generation !== generation) this.diagnostics.lateUpdates++; return; } if (current) await this.destroyView(node.id); const controller = new AbortController(); const signal = mergeSignals(this.instanceAbort.signal, controller.signal); const context = this.context(signal); const view = await renderer.create(node, context); if (this.destroyed || signal.aborted) { this.diagnostics.lateUpdates++; renderer.destroy(view, context); return; } const entry: Entry = { node, view, renderer, controller, generation: 1 }; this.entries.set(node.id, entry); this.activeViews.set(node.id, view); this.world?.addChild?.(view.displayObject); this.diagnostics.creates++; await renderer.update(view, node, context); }
  private async destroyView(id: string): Promise<void> { const entry = this.entries.get(id); if (!entry) return; entry.controller.abort(); this.entries.delete(id); this.activeViews.delete(id); this.world?.removeChild?.(entry.view.displayObject); entry.renderer.destroy(entry.view, this.context(entry.controller.signal)); this.diagnostics.destroys++; }
  private async applyCulling(): Promise<void> { if (!this.visibleBounds) return; const visible = new Set(this.options.cullingQuery ? this.options.cullingQuery(this.visibleBounds) : this.spatialIndex.query(this.visibleBounds)); for (const [id, entry] of this.entries) entry.view.displayObject.visible = visible.has(id); }
  private async reconcileActiveSet(): Promise<void> { if (!this.snapshot) return; const retained = new Set<string>(); const ids = this.visibleBounds ? new Set(this.options.cullingQuery ? this.options.cullingQuery(this.visibleBounds) : this.spatialIndex.query(this.visibleBounds)) : new Set(this.nodesById.keys()); for (const id of ids) { const node = this.nodesById.get(id); if (node && this.shouldActivate(node)) { retained.add(id); await this.ensureView(node); } } for (const id of [...this.entries.keys()]) if (!retained.has(id)) await this.destroyView(id); }
  private shouldActivate(node: Readonly<BoardNode>): boolean { return node.visible !== false && (!this.visibleBounds || new Set(this.options.cullingQuery ? this.options.cullingQuery(this.visibleBounds) : this.spatialIndex.query(this.visibleBounds)).has(node.id)); }
  private rebuildSpatialIndex(snapshot: Readonly<BoardDocument>): void { this.spatialIndex.rebuild(snapshot.nodes.map((node) => ({ ...this.getBounds(node), id: node.id })));
  }
  private async captureFrame(target: PixiDisplayObject, frame: WorldBounds | undefined, scale: number, request: CaptureRequest, signal: AbortSignal, requestId?: string): Promise<RendererCaptureResult> { if (signal.aborted) throw new DOMException("Aborted", "AbortError"); const value = this.options.capture ? await this.options.capture({ target, frame, scale, format: "png" }, request, signal) : await this.captureWithPixi(target, frame, scale); if (signal.aborted) throw new DOMException("Aborted", "AbortError"); return { ...value, revision: this.snapshot?.revision ?? 0, ...(requestId ? { requestId } : {}) }; }
  private async captureWithPixi(target: PixiDisplayObject, frame: WorldBounds | undefined, scale: number): Promise<{ dataUrl: string; mimeType: string }> { const extract = this.app?.renderer?.extract?.base64; if (!extract) throw new Error("Capture is unavailable without a Pixi extract adapter"); const dataUrl = await extract.call(this.app!.renderer!.extract, { target, frame, format: "png", resolution: scale }); return { dataUrl, mimeType: "image/png" }; }
  private context(signal: AbortSignal): PixiNodeRendererContext { if (!this.viewFactory) throw new Error("Renderer is not initialized"); return { signal, assets: { acquireTexture: this.options.acquireTexture ?? (async () => ({})) }, invalidate: () => this.options.onInvalidate?.(), lod: {}, diagnostics: this.diagnostics, display: this.viewFactory }; }
  private assertAlive(): void { if (this.destroyed) throw new Error("Renderer has been destroyed"); if (!this.app) throw new Error("Renderer is not initialized"); }
}
function contains(b: WorldBounds, p: Point): boolean { return p.x >= b.minX && p.x <= b.maxX && p.y >= b.minY && p.y <= b.maxY; }
function mergeSignals(...signals: AbortSignal[]): AbortSignal { const controller = new AbortController(); const abort = () => controller.abort(); for (const signal of signals) { if (signal.aborted) controller.abort(); else signal.addEventListener("abort", abort, { once: true }); } return controller.signal; }
function sameAssetRefs(a: BoardNode["assetRefs"], b: BoardNode["assetRefs"]): boolean { return JSON.stringify(a ?? {}) === JSON.stringify(b ?? {}); }
