import { rotatedRectBounds, type BoardNode, type BoardDocument, type BoardChangeSet, type WorldBounds, type Point, type AssetRef, type NodeTypeRegistry } from "@pixi-board/core";
import { NodeRendererRegistry } from "./registry";
import { registerBuiltinRenderers } from "./builtins";
import type { CullingQuery, PixiApplication, PixiApplicationFactory, PixiDisplayObject, PixiNodeRendererContext, PixiNodeView, PixiViewFactory, RendererDiagnostics, TextureLease } from "./types";
type Entry = { node: Readonly<BoardNode>; view: PixiNodeView; renderer: any; controller: AbortController; generation: number };
export type PixiBoardRendererOptions = { applicationFactory: PixiApplicationFactory; viewFactory: PixiViewFactory; cullingQuery?: CullingQuery; acquireTexture?: (ref: AssetRef, options?: Record<string, unknown>) => Promise<TextureLease>; onInvalidate?: () => void; registry?: NodeRendererRegistry; nodeTypes?: NodeTypeRegistry };
export class PixiBoardRenderer {
  readonly registry: NodeRendererRegistry; readonly diagnostics: RendererDiagnostics = { creates: 0, updates: 0, destroys: 0, lateUpdates: 0 }; readonly activeViews = new Map<string, PixiNodeView>();
  private readonly options: PixiBoardRendererOptions; private readonly instanceAbort = new AbortController(); private readonly entries = new Map<string, Entry>(); private app?: PixiApplication; private world?: PixiDisplayObject; private snapshot?: Readonly<BoardDocument>; private visibleBounds?: WorldBounds; private destroyed = false;
  constructor(options: PixiBoardRendererOptions) { this.options = options; this.registry = options.registry ?? new NodeRendererRegistry(); registerBuiltinRenderers(this.registry); }
  async init(): Promise<void> { if (this.destroyed) throw new Error("Renderer has been destroyed"); this.app = await this.options.applicationFactory(); await this.app.init?.({ preference: "webgl", antialias: false, powerPreference: "high-performance" }); this.world = this.options.viewFactory.createContainer(); this.app.stage.addChild?.(this.world); }
  async rebuild(snapshot: Readonly<BoardDocument>): Promise<void> { this.assertAlive(); this.snapshot = snapshot; for (const id of [...this.entries.keys()]) await this.destroyView(id); for (const node of snapshot.nodes) if (this.shouldActivate(node)) await this.ensureView(node); }
  async apply(snapshot: Readonly<BoardDocument>, changeSet?: BoardChangeSet): Promise<void> { this.assertAlive(); if (!changeSet || !this.snapshot || changeSet.revision !== this.snapshot.revision + 1) return this.rebuild(snapshot); this.snapshot = snapshot; for (const id of changeSet.removedNodeIds) await this.destroyView(id); const ids = new Set([...changeSet.addedNodeIds, ...changeSet.updatedNodeIds, ...changeSet.assetChangedNodeIds]); for (const id of ids) { const node = snapshot.nodes.find((n) => n.id === id); if (node && this.shouldActivate(node)) await this.ensureView(node); else await this.destroyView(id); } await this.applyCulling(); }
  async setVisibleBounds(bounds: WorldBounds | undefined): Promise<void> { this.visibleBounds = bounds; if (this.snapshot) { for (const node of this.snapshot.nodes) { if (this.shouldActivate(node)) await this.ensureView(node); else await this.destroyView(node.id); } } await this.applyCulling(); }
  setCullingQuery(query: CullingQuery | undefined): void { this.options.cullingQuery = query; }
  async refreshRegisteredTypes(): Promise<void> { if (this.snapshot) await this.rebuild(this.snapshot); }
  getBounds(node: Readonly<BoardNode>): WorldBounds { const definition = this.options.nodeTypes?.get(node.type); return definition ? definition.getBounds(node as BoardNode<any>) : rotatedRectBounds(node); }
  hitTest(worldPoint: Point): string | undefined { for (const [id, entry] of this.entries) if (entry.renderer.hitTest?.(entry.node, worldPoint) ?? contains(rotatedRectBounds(entry.node), worldPoint)) return id; return undefined; }
  async destroy(): Promise<void> { if (this.destroyed) return; this.destroyed = true; this.instanceAbort.abort(); for (const id of [...this.entries.keys()]) await this.destroyView(id); this.world?.destroy?.({ children: true }); this.app?.destroy?.(true); this.entries.clear(); this.activeViews.clear(); }
  private async ensureView(node: Readonly<BoardNode>): Promise<void> { const renderer = this.registry.get(node.type) ?? this.registry.get("unknown-node")!; const current = this.entries.get(node.id); if (current && current.renderer === renderer) { current.node = node; const generation = ++current.generation; this.diagnostics.updates++; await renderer.update(current.view, node, this.context(current.controller.signal)); if (this.entries.get(node.id) !== current || current.generation !== generation) this.diagnostics.lateUpdates++; return; } if (current) await this.destroyView(node.id); const controller = new AbortController(); const signal = mergeSignals(this.instanceAbort.signal, controller.signal); const context = this.context(signal); const view = await renderer.create(node, context); if (this.destroyed || signal.aborted) { this.diagnostics.lateUpdates++; renderer.destroy(view, context); return; } const entry: Entry = { node, view, renderer, controller, generation: 1 }; this.entries.set(node.id, entry); this.activeViews.set(node.id, view); this.world?.addChild?.(view.displayObject); this.diagnostics.creates++; await renderer.update(view, node, context); }
  private async destroyView(id: string): Promise<void> { const entry = this.entries.get(id); if (!entry) return; entry.controller.abort(); this.entries.delete(id); this.activeViews.delete(id); this.world?.removeChild?.(entry.view.displayObject); entry.renderer.destroy(entry.view, this.context(entry.controller.signal)); this.diagnostics.destroys++; }
  private async applyCulling(): Promise<void> { if (!this.visibleBounds) return; const visible = this.options.cullingQuery ? new Set(this.options.cullingQuery(this.visibleBounds)) : undefined; for (const [id, entry] of this.entries) entry.view.displayObject.visible = visible ? visible.has(id) : true; }
  private shouldActivate(node: Readonly<BoardNode>): boolean { return node.visible !== false && (!this.visibleBounds || !this.options.cullingQuery || new Set(this.options.cullingQuery(this.visibleBounds)).has(node.id)); }
  private context(signal: AbortSignal): PixiNodeRendererContext { return { signal, assets: { acquireTexture: this.options.acquireTexture ?? (async () => ({})) }, invalidate: () => this.options.onInvalidate?.(), lod: {}, diagnostics: this.diagnostics, display: this.options.viewFactory }; }
  private assertAlive(): void { if (this.destroyed) throw new Error("Renderer has been destroyed"); if (!this.app) throw new Error("Renderer is not initialized"); }
}
function contains(b: WorldBounds, p: Point): boolean { return p.x >= b.minX && p.x <= b.maxX && p.y >= b.minY && p.y <= b.maxY; }
function mergeSignals(...signals: AbortSignal[]): AbortSignal { const controller = new AbortController(); const abort = () => controller.abort(); for (const signal of signals) { if (signal.aborted) controller.abort(); else signal.addEventListener("abort", abort, { once: true }); } return controller.signal; }
