import type { AssetRef, BoardChangeSet, BoardNode, BoardDocument, JsonValue, Point, WorldBounds } from "@pixi-board/core";
export type PixiDisplayObject = { visible?: boolean; x?: number; y?: number; rotation?: number; zIndex?: number; addChild?(child: PixiDisplayObject): void; removeChild?(child: PixiDisplayObject): void; destroy?(options?: unknown): void; [key: string]: unknown };
export type PixiApplication = { stage: PixiDisplayObject; init?(options?: Record<string, unknown>): Promise<void> | void; destroy?(removeView?: boolean): void; canvas?: unknown; view?: unknown };
export type PixiViewFactory = { createContainer(): PixiDisplayObject; createRect?(width: number, height: number, fill: number | string): PixiDisplayObject; createImage?(ref: AssetRef | undefined, node: Readonly<BoardNode>): PixiDisplayObject | Promise<PixiDisplayObject>; createText?(text: string, style?: Record<string, unknown>): PixiDisplayObject };
export type PixiApplicationFactory = () => PixiApplication | Promise<PixiApplication>;
export type TextureLease = { texture?: unknown; release?: () => void };
export type RendererDiagnostics = { creates: number; updates: number; destroys: number; lateUpdates: number };
export type PixiNodeRendererContext = { signal: AbortSignal; assets: { acquireTexture(ref: AssetRef, options?: Record<string, unknown>): Promise<TextureLease> }; invalidate(): void; lod: { level?: number; scale?: number }; diagnostics: RendererDiagnostics; display: PixiViewFactory };
export type PixiNodeView<State = unknown> = { displayObject: PixiDisplayObject; state: State };
export type PixiNodeRenderer<Props extends JsonValue = JsonValue, State = unknown> = { create(node: Readonly<BoardNode<Props>>, context: PixiNodeRendererContext): PixiNodeView<State> | Promise<PixiNodeView<State>>; update(view: PixiNodeView<State>, node: Readonly<BoardNode<Props>>, context: PixiNodeRendererContext): void | Promise<void>; destroy(view: PixiNodeView<State>, context: PixiNodeRendererContext): void; hitTest?(node: Readonly<BoardNode<Props>>, worldPoint: Point): boolean };
export type CullingQuery = (bounds: WorldBounds) => Iterable<string>;
export type RendererSnapshot = Readonly<BoardDocument>;
export type RendererChangeSet = BoardChangeSet;
