export const PLUGIN_API_VERSION = "3" as const;
export type PluginPermission = "canvas.read" | "canvas.write" | "events.subscribe" | "panel.register" | "tool.register" | "process.spawn" | "renderer:trusted";
export type PluginManifest = { id: string; name: string; version: string; apiVersion: typeof PLUGIN_API_VERSION; permissions: readonly PluginPermission[]; contributions?: { panels?: readonly string[]; tools?: readonly string[]; processes?: readonly string[] } };
export type PluginEvent = { type: "change"; revision: number; changeSet: unknown } | { type: "selection:change"; nodeIds: readonly string[]; previousNodeIds: readonly string[] } | { type: "viewport:change"; viewport: unknown; previousViewport: unknown };
export type PluginEventSource = { on(event: "change" | "selection:change" | "viewport:change", listener: (event: PluginEvent) => void): () => void };
export type PluginCanvas = { read(input?: unknown, options?: unknown): Promise<{ nodes: readonly unknown[]; page: { hasMore: boolean; nextCursor?: string }; revision: number; requestId?: string }>; create(input: unknown, options?: unknown): Promise<unknown>; update(input: unknown, options?: unknown): Promise<unknown>; delete(input: unknown, options?: unknown): Promise<unknown> };
export type PluginToolHandler = (input: unknown) => unknown | Promise<unknown>;
export type PluginProcessRequest = { command: string; args?: readonly string[]; cwd?: string; env?: Readonly<Record<string, string>> };
export type PluginProcessHandle = { stop(): void | Promise<void> };
export type PluginContext = { manifest: Readonly<PluginManifest>; canvas: PluginCanvas; events: { subscribe(event: "change" | "selection:change" | "viewport:change", listener: (event: PluginEvent) => void): () => void }; panels: { register(id: string): () => void }; tools: { register(id: string, handler?: PluginToolHandler): () => void }; processes: { start(id: string, request: PluginProcessRequest): Promise<PluginProcessHandle> } };
export type PluginDefinition = { manifest: PluginManifest; start(context: PluginContext): void | Promise<void>; stop?(): void | Promise<void> };
export type SerializedPluginError = { code: string; name: string; message: string; details?: Record<string, unknown> };
export function assertV3Manifest(value: unknown): asserts value is PluginManifest { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Plugin manifest must be an object"); const manifest = value as Partial<PluginManifest>; if (manifest.apiVersion !== PLUGIN_API_VERSION) throw new Error("Only Plugin API v3 manifests are accepted"); for (const field of ["id", "name", "version"] as const) if (typeof manifest[field] !== "string" || !manifest[field]?.trim()) throw new Error(`Plugin manifest requires ${field}`); if (!Array.isArray(manifest.permissions)) throw new Error("Plugin manifest permissions must be an array"); }
export function serializePluginError(error: unknown): SerializedPluginError { if (error instanceof Error) return { code: "INTERNAL_ERROR", name: error.name, message: error.message }; return { code: "INTERNAL_ERROR", name: "Error", message: String(error) }; }
